VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "OddsSanrentan"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Kumi As String
Public Umaban1 As String
Public Umaban2 As String
Public Umaban3 As String
Public OddsSanrentan As String

Public Property Get Self() As OddsSanrentan
    Set Self = Me
End Property

