VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "RaceUma"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public strdate As String
Public nameJyo As String
Public racenum As String
Public Umaban As String
Public Ninki As String
Public Bamei As String
Public KettoNum As String

Public Property Get Self() As RaceUma
    Set Self = Me
End Property
